#Version:1
#author:clc
#base images
FROM 33b6076e0a28
MAINTAINER 474335602@qq.com
ENV NGINX_VERSION 1.10.1
#commands

#env-pre
RUN rm -rf /var/cache/yum/x86_64/6/*　&& \
builddeps=" \
pcre \
pcre-devel \
openssl \
openssl-devel \
tar \
gcc \
" \
&& yum install -y ${builddeps} && \
rm -rf /var/cache/yum/x86_64/6/*  && \
rm -rf /home/clc/tools/*

RUN curl -fSL http://nginx.org/download/nginx-1.10.1.tar.gz -o nginx-1.10.1.tar.gz \
&& tar -zxvf nginx-1.10.1.tar.gz && \
cd nginx-1.10.1  && \
./configure --prefix=/application/nginx-1.10.1 \
--user=nginx \
--group=nginx \
--with-http_ssl_module \
--with-http_stub_status_module && \
make && make install && \
ln -s /application/nginx-1.10.1 /application/nginx && \
rm -rf /nginx-1.10.1*

#supervisor configure


EXPOSE 80 9000
ENTRYPOINT   /application/nginx/sbin/nginx && /application/php/sbin/php-fpm -F 
